[build-system]
requires = ["setuptools>=75"]
build-backend = "setuptools.build_meta"

[project]
name = "ragvault-backend"
version = "0.1.0"
description = "RAGVault backend"
requires-python = ">=3.14"

[tool.setuptools.packages.find]
where = ["."]
include = ["app", "app.*"]
[tool.pytest.ini_options]
python_functions = ["test_*","check_*"]
