"""multiple upgrades done which i do not remember

Revision ID: 02cc849368e3
Revises: 
Create Date: 2026-07-02 15:22:43.138077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02cc849368e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_jobs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('ingestion_jobs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('password', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=20), nullable=False))
    op.create_unique_constraint('uq_phone_email', 'users', ['phone', 'email'])
    op.create_unique_constraint(None, 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint('uq_phone_email', 'users', type_='unique')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'password')
    op.drop_column('ingestion_jobs', 'completed_at')
    op.drop_column('ingestion_jobs', 'updated_at')
    # ### end Alembic commands ###
