"""remove attempts from EmailVerificatonOtp

Revision ID: 531b5d6745c0
Revises: c68b63e1a96c
Create Date: 2026-08-14 23:56:22.157360

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '531b5d6745c0'
down_revision: str | Sequence[str] | None = 'c68b63e1a96c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
