"""making phone,email and username uq in users

Revision ID: 7acb1d4f6f8f
Revises: d4f099649987
Create Date: 2026-07-12 15:00:32.462277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7acb1d4f6f8f'
down_revision: Union[str, Sequence[str], None] = 'd4f099649987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_email', 'users', ['email'])
    op.create_unique_constraint('uq_phone', 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_phone', 'users', type_='unique')
    op.drop_constraint('uq_email', 'users', type_='unique')
    # ### end Alembic commands ###
