"""setting doc id in ingestion nullable

Revision ID: 7ec0d97a1c3d
Revises: 02cc849368e3
Create Date: 2026-07-05 12:14:36.423981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ec0d97a1c3d'
down_revision: Union[str, Sequence[str], None] = '02cc849368e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingestion_jobs', 'document_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('ingestion_jobs_document_id_fkey'), 'ingestion_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'ingestion_jobs', 'documents', ['document_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingestion_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('ingestion_jobs_document_id_fkey'), 'ingestion_jobs', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ingestion_jobs', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
