"""replace user_id with email in EmailVerificatonOtp

Revision ID: a13e67c84fa2
Revises: 531b5d6745c0
Create Date: 2026-08-19 13:10:57.914277

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a13e67c84fa2'
down_revision: str | Sequence[str] | None = '531b5d6745c0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verification_otp', sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False))
    op.drop_constraint(op.f('email_verification_otp_user_id_fkey'), 'email_verification_otp', type_='foreignkey')
    op.drop_column('email_verification_otp', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verification_otp', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('email_verification_otp_user_id_fkey'), 'email_verification_otp', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('email_verification_otp', 'email')
    # ### end Alembic commands ###
