"""making phone,email and username uq in users

Revision ID: a683be24eaea
Revises: c208e58f1609
Create Date: 2026-07-12 12:49:27.606703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a683be24eaea'
down_revision: Union[str, Sequence[str], None] = 'c208e58f1609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_phone_email'), 'users', type_='unique')
    op.drop_constraint(op.f('users_user_name_key'), 'users', type_='unique')
    op.create_unique_constraint('uq_user_name', 'users', ['user_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_name', 'users', type_='unique')
    op.create_unique_constraint(op.f('users_user_name_key'), 'users', ['user_name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_phone_email'), 'users', ['phone', 'email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
