"""idempotency type chance

Revision ID: c68b63e1a96c
Revises: 7acb1d4f6f8f
Create Date: 2026-07-17 23:37:38.023994

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c68b63e1a96c'
down_revision: str | Sequence[str] | None = '7acb1d4f6f8f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # New fixed code
# op.execute('ALTER TABLE ingestion_jobs ALTER COLUMN idempotency_key TYPE UUID USING idempotency_key::uuid')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingestion_jobs', 'idempotency_key',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
