"""UserSession:Replacing refresh token with refresh_token_jti

Revision ID: fc2a88c91b94
Revises: a78942a4b205
Create Date: 2026-08-24 00:14:55.950263

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fc2a88c91b94'
down_revision: str | Sequence[str] | None = 'a78942a4b205'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('refresh_token_jti', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_user_sessions_refresh_token'), table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_refresh_token_jti'), 'user_sessions', ['refresh_token_jti'], unique=True)
    op.drop_column('user_sessions', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_sessions_refresh_token_jti'), table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_refresh_token'), 'user_sessions', ['refresh_token'], unique=True)
    op.drop_column('user_sessions', 'refresh_token_jti')
    # ### end Alembic commands ###
